"""51Job apply/open and controlled resume-submit flows."""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import parse_qsl, urlencode, urldefrag, urlsplit, urlunsplit

from jobagent.domain.models import SendAttempt
from jobagent.drivers.boss import create_driver

from .audit import Job51AuditEvent, Job51AuditLog


@dataclass
class Job51ApplyOpenResult:
    ok: bool
    opened: int
    planned: int
    failed: int
    total: int
    events: list[dict[str, Any]] = field(default_factory=list)
    handoff: list[dict[str, Any]] = field(default_factory=list)
    mode: str = "manual_apply_open"
    platform: str = "51job"
    next_suggested: str = "Review opened 51Job pages manually, then run `jobagent 51job audit`."
    requires_user_action: bool = False
    user_prompt: str = ""

    def to_payload(self) -> dict[str, Any]:
        payload = {
            "ok": self.ok,
            "platform": self.platform,
            "mode": self.mode,
            "total": self.total,
            "planned": self.planned,
            "opened": self.opened,
            "failed": self.failed,
            "requires_user_action": self.requires_user_action,
            "handoff": self.handoff,
            "events": self.events,
            "next_suggested": self.next_suggested,
        }
        if self.user_prompt:
            payload["user_prompt"] = self.user_prompt
        return payload


class Job51ApplyOpener:
    def __init__(self, driver: Any | None = None, audit_log: Job51AuditLog | None = None):
        self.driver = driver
        self.audit_log = audit_log or Job51AuditLog()

    def open_jobs(self, jobs: list[dict[str, Any]], limit: int = 5, start: int = 0, wait_seconds: int = 3, dry_run: bool = False) -> Job51ApplyOpenResult:
        selected = jobs[max(0, start): max(0, start) + max(1, limit)]
        events: list[dict[str, Any]] = []
        handoff_items: list[dict[str, Any]] = []
        opened = planned = failed = 0
        for index, job in enumerate(selected, start=max(0, start)):
            url = _job51_open_url(job)
            handoff = _handoff_evidence(job)
            if not url:
                failed += 1
                event = self._event_from_job(job, status="failed", error="missing_job_url", message="Cannot open 51Job job without url.", evidence={"index": index, **handoff})
            elif dry_run:
                planned += 1
                event = self._event_from_job(job, status="planned", message="dry_run", evidence={"index": index, **handoff})
            else:
                driver = self.driver or create_driver(platform="51job")
                self.driver = driver
                result = driver.open_url_in_new_tab(url, wait_seconds=wait_seconds)
                if result.get("ok"):
                    opened += 1
                    event = self._event_from_job(job, status="opened", message="Opened for manual review.", evidence={"index": index, **handoff, "open_result": result})
                else:
                    failed += 1
                    event = self._event_from_job(job, status="failed", error=str(result.get("error") or "open_failed"), message="Failed to open 51Job page.", evidence={"index": index, **handoff, "open_result": result})
            self.audit_log.append(event)
            events.append(event.to_dict())
            handoff_items.append(_handoff_item(job, index=index, status=event.status, error=event.error))

        return Job51ApplyOpenResult(
            ok=failed == 0,
            opened=opened,
            planned=planned,
            failed=failed,
            total=len(selected),
            events=events,
            handoff=handoff_items,
            next_suggested="Review handoff, then rerun without `--dry-run` to open 51Job pages." if dry_run else "Review opened 51Job pages manually, then run `jobagent 51job audit`.",
            requires_user_action=opened > 0,
            user_prompt="" if dry_run else "请在已打开的前程无忧/51Job 页面中人工确认岗位。51Job 网页端“去聊聊”只是扫码引导，handoff 里的 greeting 仅作为投递前审阅备注，不会发送到 51Job 页面。",
        )

    def _event_from_job(self, job: dict[str, Any], status: str, message: str = "", error: str = "", evidence: dict[str, Any] | None = None) -> Job51AuditEvent:
        return Job51AuditEvent(
            action="apply_open",
            status=status,
            job_url=str(job.get("url") or ""),
            job_name=str(job.get("name") or job.get("title") or ""),
            company=str(job.get("company") or ""),
            error=error,
            message=message,
            evidence=evidence or {},
        )


class Job51ApplySender:
    """Controlled 51Job resume submission.

    51Job's web page exposes a real `投递` button and a `去聊聊` QR handoff.
    The greeting generated by `greet preview` is therefore a review note only;
    it is never filled into the 51Job web page.
    """

    def __init__(self, driver: Any | None = None, audit_log: Job51AuditLog | None = None):
        self.driver = driver
        self.audit_log = audit_log or Job51AuditLog()

    def send_batch(
        self,
        jobs: list[dict[str, Any]],
        limit: int = 5,
        start: int = 0,
        wait_seconds: int = 3,
        dry_run: bool = False,
        skip_delivered: bool = True,
        stop_on_failure: bool = True,
    ) -> list[SendAttempt]:
        selected = jobs[max(0, start): max(0, start) + max(1, limit)]
        delivered_keys = self.audit_log.delivered_apply_send_keys() if skip_delivered else set()
        attempts: list[SendAttempt] = []
        for index, job in enumerate(selected, start=max(0, start)):
            message = str(job.get("cloud_greeting") or job.get("greeting") or "")
            key = _job51_job_key(job)
            url = _job51_open_url(job)
            if skip_delivered and key and key in delivered_keys:
                attempt = SendAttempt(job_url=url, message=message, delivered=False, error="already_delivered")
                attempt.steps = [{"step": "skip_51job_apply_send", "ok": True, "reason": "already_delivered", "job_id": key}]
                status = "skipped"
                audit_message = "Skipped because this 51Job job was already delivered."
            else:
                attempt = self._send_one(job, message, wait_seconds=wait_seconds, dry_run=dry_run)
                status = "planned" if dry_run else ("delivered" if attempt.delivered else "failed")
                audit_message = "dry_run" if dry_run else ("Delivered." if attempt.delivered else "Failed.")
                if attempt.delivered and key:
                    delivered_keys.add(key)
            attempts.append(attempt)
            self.audit_log.append(
                Job51AuditEvent(
                    action="apply_send",
                    status=status,
                    job_url=attempt.job_url,
                    job_name=str(job.get("name") or job.get("title") or ""),
                    company=str(job.get("company") or ""),
                    error=attempt.error,
                    message=audit_message,
                    evidence={
                        "index": index,
                        "job_id": key,
                        "has_greeting": bool(message.strip()),
                        "greeting_generated": bool(message.strip()),
                        "greeting": message,
                        "greeting_role": "review_note",
                        "submit_action": "resume_submit",
                        "chat_action": "qr_only",
                        "score": job.get("score"),
                        "match_level": job.get("match_level") or job.get("recommendation") or job.get("cloud_recommendation"),
                        "steps": attempt.steps,
                    },
                )
            )
            if stop_on_failure and not dry_run and status == "failed":
                break
        return attempts

    def _send_one(self, job: dict[str, Any], message: str, wait_seconds: int = 3, dry_run: bool = False) -> SendAttempt:
        url = _job51_open_url(job)
        job_id = _job51_job_key(job)
        attempt = SendAttempt(job_url=url, message=message, delivered=False)
        if not url:
            attempt.error = "missing_job_url"
            return attempt
        if dry_run:
            attempt.error = "dry_run"
            attempt.steps = [{"step": "plan_51job_apply_send", "ok": True, "url": url, "job_id": job_id}]
            return attempt

        driver = self.driver or create_driver(platform="51job")
        self.driver = driver
        open_result = driver.open_url_in_new_tab(url, wait_seconds=wait_seconds)
        steps: list[dict[str, Any]] = [{"step": "open_51job_url", **open_result}]
        if not open_result.get("ok"):
            attempt.error = str(open_result.get("error") or "open_51job_url_failed")
            attempt.steps = steps
            return attempt

        inspect_before = _exec_job51_js(driver, _job51_apply_inspect_script(job_id))
        steps.append({"step": "inspect_before_apply", **inspect_before})
        if _job51_page_requires_login(inspect_before):
            attempt.error = "login_required"
            attempt.steps = steps
            return attempt
        if inspect_before.get("requires_user_action"):
            attempt.error = str(inspect_before.get("user_action") or "user_action_required")
            attempt.steps = steps
            return attempt
        if _job51_delivery_detected(inspect_before):
            attempt.delivered = True
            attempt.steps = steps
            return attempt

        if message.strip():
            steps.append({"step": "job51_greeting_not_supported", "ok": True, "reason": "job51_chat_is_qr_only"})
        click_result = _exec_job51_js(driver, _job51_apply_click_script(job_id))
        steps.append({"step": "click_51job_apply", **click_result})
        if not click_result.get("ok") and click_result.get("error") == "job51_card_not_found":
            recovery_url = _job51_recovery_url(job)
            if recovery_url and recovery_url != url:
                recovery_open = driver.open_url_in_new_tab(recovery_url, wait_seconds=wait_seconds)
                steps.append({"step": "open_51job_recovery_url", **recovery_open})
                if not recovery_open.get("ok"):
                    attempt.error = str(recovery_open.get("error") or "open_51job_recovery_url_failed")
                    attempt.steps = steps
                    return attempt
                recovery_state = _exec_job51_js(driver, _job51_apply_inspect_script(job_id))
                steps.append({"step": "inspect_before_recovery_apply", **recovery_state})
                if _job51_page_requires_login(recovery_state):
                    attempt.error = "login_required"
                    attempt.steps = steps
                    return attempt
                if recovery_state.get("requires_user_action"):
                    attempt.error = str(recovery_state.get("user_action") or "user_action_required")
                    attempt.steps = steps
                    return attempt
                if _job51_delivery_detected(recovery_state):
                    attempt.delivered = True
                    attempt.steps = steps
                    return attempt
                click_result = _exec_job51_js(driver, _job51_apply_click_script(job_id))
                steps.append({"step": "click_51job_apply_recovery", **click_result})
        if not click_result.get("ok"):
            attempt.error = str(click_result.get("error") or "job51_apply_button_not_found")
            attempt.steps = steps
            return attempt
        time.sleep(1.5)
        after = _exec_job51_js(driver, _job51_apply_inspect_script(job_id))
        steps.append({"step": "inspect_after_apply", **after})
        if _job51_delivery_detected(after):
            attempt.delivered = True
        else:
            attempt.error = str(after.get("user_action") or after.get("error") or "delivery_not_verified")
        attempt.steps = steps
        return attempt


def _handoff_evidence(job: dict[str, Any]) -> dict[str, Any]:
    greeting = str(job.get("cloud_greeting") or job.get("greeting") or "")
    return {
        "job_id": _job51_job_key(job),
        "has_greeting": bool(greeting),
        "greeting": greeting,
        "score": job.get("score"),
        "match_level": job.get("match_level") or job.get("recommendation") or job.get("cloud_recommendation"),
        "chat_action": "qr_only",
        "submit_action": "resume_submit",
    }


def _handoff_item(job: dict[str, Any], index: int, status: str, error: str = "") -> dict[str, Any]:
    return {
        "index": index,
        "status": status,
        "action": "review_51job_fit_before_resume_submit",
        "job_name": str(job.get("name") or job.get("title") or ""),
        "company": str(job.get("company") or ""),
        "url": str(job.get("url") or ""),
        "error": error,
        **_handoff_evidence(job),
    }


def _job51_job_key(job: dict[str, Any]) -> str:
    raw = job.get("raw_data") if isinstance(job.get("raw_data"), dict) else {}
    return str(job.get("job_id") or job.get("jobId") or raw.get("jobId") or _fragment_job_id(str(job.get("url") or "")) or job.get("url") or "").strip()


def _fragment_job_id(url: str) -> str:
    if "#jobId=" in url:
        return url.split("#jobId=", 1)[-1].strip()
    return ""


def _job51_open_url(job: dict[str, Any]) -> str:
    url = str(job.get("url") or "")
    base, _frag = urldefrag(url)
    return base or url


def _job51_recovery_url(job: dict[str, Any]) -> str:
    title = str(job.get("name") or job.get("title") or "").strip()
    base_url = _job51_open_url(job)
    if not title or not base_url:
        return ""
    parts = urlsplit(base_url)
    query = dict(parse_qsl(parts.query, keep_blank_values=True))
    query["keyword"] = title
    query.pop("pageNum", None)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query), ""))


def _exec_job51_js(driver: Any, script: str) -> dict[str, Any]:
    if not hasattr(driver, "_exec_js"):
        return {"ok": False, "error": "driver_js_not_supported"}
    result = driver._exec_js(script)
    if isinstance(result, dict) and isinstance(result.get("raw"), str):
        try:
            parsed = json.loads(result["raw"])
            return parsed if isinstance(parsed, dict) else {"ok": False, "error": "unexpected_js_result"}
        except Exception as e:
            return {"ok": False, "error": str(e)}
    return result if isinstance(result, dict) else {"ok": False, "error": "unexpected_js_result"}


def _job51_page_requires_login(state: dict[str, Any]) -> bool:
    if state.get("loginRequired") is True:
        return True
    text = f"{state.get('title') or ''}\n{state.get('bodySnippet') or ''}"
    return any(token in text for token in ("登录/注册", "请登录", "扫码登录", "验证码登录", "手机验证码", "安全验证", "滑块"))


def _job51_delivery_detected(state: dict[str, Any]) -> bool:
    if state.get("delivered") is True:
        return True
    text = f"{state.get('title') or ''}\n{state.get('bodySnippet') or ''}"
    return any(token in text for token in ("投递成功", "已投递", "简历投递成功", "申请成功"))


def _job51_apply_inspect_script(job_id: str = "") -> str:
    safe_job_id = json.dumps(job_id)
    return f"""
    (function(){{
      const jobId = {safe_job_id};
      const clean = (value) => String(value || '').replace(/\\s+/g, ' ').trim();
      const href = location.href || '';
      const title = document.title || '';
      const bodyText = clean(document.body && (document.body.innerText || document.body.textContent));
      function visible(el) {{
        if (!el) return false;
        const style = window.getComputedStyle(el);
        const rect = el.getBoundingClientRect();
        return style.display !== 'none' && style.visibility !== 'hidden' && rect.width > 8 && rect.height > 8;
      }}
      const loginRequired = /passport|login/.test(href) || (/登录[/]注册|请登录|扫码登录|验证码登录/.test(bodyText.slice(0, 1000)) && !document.querySelector('.joblist-item'));
      const delivered = /投递成功|已投递|简历投递成功|申请成功/.test(bodyText);
      const visibleDialogs = Array.from(document.querySelectorAll('[role="dialog"], .el-dialog, .ant-modal, .dialog, .modal'))
        .filter(visible);
      const resumeDialogText = clean(visibleDialogs.map((node) => node.innerText || node.textContent).join(' '));
      const requiresResume = /请选择简历|上传简历|完善简历|创建简历|选择附件简历/.test(resumeDialogText) && !delivered;
      const requiresCaptcha = /验证码登录|手机验证码|安全验证|滑块|Security Verification|check the box below/.test(title + '\\n' + bodyText);
      return JSON.stringify({{
        ok: true,
        href,
        title,
        jobId,
        loginRequired,
        delivered,
        requires_user_action: requiresResume || requiresCaptcha,
        user_action: requiresCaptcha ? 'captcha_required' : (requiresResume ? 'resume_selection_required' : ''),
        bodySnippet: bodyText.slice(0, 1400)
      }});
    }})()
    """


def _job51_apply_click_script(job_id: str = "") -> str:
    safe_job_id = json.dumps(job_id)
    return f"""
    (function(){{
      const jobId = {safe_job_id};
      const clean = (value) => String(value || '').replace(/\\s+/g, ' ').trim();
      function visible(el) {{
        if (!el) return false;
        const style = window.getComputedStyle(el);
        const rect = el.getBoundingClientRect();
        return style.display !== 'none' && style.visibility !== 'hidden' && rect.width > 8 && rect.height > 8;
      }}
      function parseSensors(el) {{
        const raw = el && el.getAttribute && el.getAttribute('sensorsdata');
        if (!raw) return {{}};
        try {{ return JSON.parse(raw); }} catch (e) {{ return {{}}; }}
      }}
      const cards = Array.from(document.querySelectorAll('.joblist-item'));
      let card = null;
      if (jobId) {{
        card = cards.find((item) => {{
          const data = parseSensors(item.querySelector('[sensorsdata]'));
          return String(data.jobId || '') === String(jobId);
        }});
      }}
      if (!card && cards.length === 1) card = cards[0];
      if (!card && jobId) {{
        return JSON.stringify({{ok:false, error:'job51_card_not_found', jobId, cardCount:cards.length}});
      }}
      const root = card || document;
      const candidates = Array.from(root.querySelectorAll('button.apply, .btn.apply, button, a, div'))
        .filter(visible)
        .filter((el) => /^投递$|立即投递|申请职位|投递简历/.test(clean(el.innerText || el.textContent)));
      const button = candidates[0];
      if (!button) return JSON.stringify({{ok:false, error:'job51_apply_button_not_found', jobId, cardText: clean(root.innerText || '').slice(0, 300)}});
      button.dispatchEvent(new MouseEvent('click', {{bubbles:true, cancelable:true, view:window}}));
      return JSON.stringify({{ok:true, clicked:clean(button.innerText || button.textContent), jobId}});
    }})()
    """
